import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter as FontSans } from "next/font/google"

export const metadata = {
  title: 'Handlelapp',
  description: 'Generated by create next app',
}
export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({ children }) {
  return (
    <html className='' lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
